apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: k8s-user
  namespace: development
rules:
  - apiGroups: [""]
    resources: ["pods","events","services"]
    verbs: ["get","watch","list","endpoints","events"]
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims"]
    verbs: ["get","watch","list","create","delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "watch", "list"]
