apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: k8s-user
  namespace: development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-user
subjects:
  - kind: ServiceAccount
    name: k8s-user
    namespace: development
